In [1]:
import pandas as pd
from personal_api import verificar_registros
from personal_api import importar_datos

In [2]:
#pasando archivo de xls a xlsx
borrador_personal = pd.read_excel('C:/wamp64/www/cos/app/Scripts/personal/planilla_personal.xls')
borrador_personal.to_excel('planilla_personal.xlsx', index=False)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
*** No CODEPAGE record, no encoding_override: will use 'iso-8859-1'

In [3]:
#leyendo el archivo y guardandolo en un dataframe
personal = pd.read_excel('C:/wamp64/www/cos/app/Scripts/personal/planilla_personal.xlsx')

#manteniendo solo las columnas necesarias
personal = personal[['legajo', 'nombres', 'apellido', 'fecha_ing', 'tipo_doc', 'nro_doc', 'convenio']]

In [4]:
personal = personal.rename(columns={'nombres': 'nombre'})

In [ ]:
# config de la api en produccion
API_URL = "https://cos.cyhsur.com/api/personal"
API_KEY = "8fyKQKXigzy0qu9JttaKzrRlkF9Z0bmy0hm9KE1D012c5e1b"

In [ ]:
#config de la api en desarrollo
API_URL2 = "http://localhost:8000/api/personal/verificar/importar"
API_KEY2 = "on4Rs05RPHjSuz4mnRe4ioMwuZAYK7OQWJtcA32a063ace84"

In [8]:
personal.head()

,legajo,nombre,apellido,fecha_ing,tipo_doc,nro_doc,convenio
0,1,GUILLERMO MARTIN,TORO,2019-03-25,DU,18365141,CONVENIO SEGURIDAD
1,3,NESTOR,ISADOR,2019-06-18,DU,21915520,CONVENIO SEGURIDAD
2,5,GUIDO,LOPARDO*,2008-11-06,DU,12345678,CONVENIO SEGURIDAD
3,6,NELSON,FLANDERS,2013-03-12,DU,29901081,CONVENIO SEGURIDAD
4,9,SEBASTIAN,RENDO,2012-07-10,DU,16315583,CONVENIO SEGURIDAD

In [ ]:
from datetime import datetime

# creando muestras para pruebas
muestra = personal.head(2).copy()

nuevo_registro1 = {
    'legajo': 9999,  
    'nombre': 'LUCIA',
    'apellido': 'PARDINI', 
    'fecha_ing': datetime(1800, 12, 12),
    'tipo_doc': 'DU',
    'nro_doc': '99999999',
    'convenio': 'CONVENIO TEST'
}

nuevo_registro2 = {
    'legajo': 9998,  
    'nombre': 'NACHO',
    'apellido': 'IGLESIAS', 
    'fecha_ing': datetime(1800, 12, 12),
    'tipo_doc': 'DU',
    'nro_doc': '99999991',
    'convenio': 'CONVENIO TEST'
}

df = pd.DataFrame([nuevo_registro1])
df2 = pd.DataFrame([nuevo_registro2])

muestra_personal = pd.concat([muestra, df, df2], ignore_index=True)
muestra_personal

,legajo,nombre,apellido,fecha_ing,tipo_doc,nro_doc,convenio
0,1,GUILLERMO MARTIN,TORO,2019-03-25,DU,18365141,CONVENIO SEGURIDAD
1,3,NESTOR,ISADOR,2019-06-18,DU,21915520,CONVENIO SEGURIDAD
2,9999,LUCIA,PARDINI,1800-12-12,DU,99999999,CONVENIO TEST
3,9998,NACHO,IGLESIAS,1800-12-12,DU,99999991,CONVENIO TEST

In [ ]:
# ver primero si el metodo de verificacion funciona (prueba)
resultados = verificar_registros(df=muestra_personal, api_url=API_URL2)
print(resultados)

{'success': True, 'estadisticas': {'total': 3, 'existentes': 2, 'nuevos': 1, 'errores': 0}, 'resultados': [{'indice': 0, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 15, 'nombre': 'GUILLERMO MARTIN', 'apellido': 'TORO', 'documento': None, 'fecha_ing': '2019-03-25', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '18365141', 'telefono': '', 'legajo': '1'}, 'datos_consultados': {'legajo': 1, 'nombre': 'GUILLERMO MARTIN', 'apellido': 'TORO', 'fecha_ing': '2019-03-25', 'tipo_doc': 'DU', 'nro_doc': '18365141', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 1, 'existe': True, 'criterio': 'legajo', 'registro_existente': {'id': 16, 'nombre': 'NESTOR', 'apellido': 'ISADOR', 'documento': None, 'fecha_ing': '2019-06-18', 'puesto': 'Sin definir', 'convenio': 'CONVENIO SEGURIDAD', 'categoria_id': None, 'estado': 'activo', 'created_at': '2025-08-25T18:59:57.000000Z', 'updated_at': '2025-08-25T18:59:57.000000Z', 'cargo': 'Sin definir', 'cliente_id': 1, 'tipo_doc': 'DU', 'nro_doc': '21915520', 'telefono': '', 'legajo': '3'}, 'datos_consultados': {'legajo': 3, 'nombre': 'NESTOR', 'apellido': 'ISADOR', 'fecha_ing': '2019-06-18', 'tipo_doc': 'DU', 'nro_doc': '21915520', 'convenio': 'CONVENIO SEGURIDAD', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}, {'indice': 2, 'existe': False, 'criterio': '', 'registro_existente': None, 'datos_consultados': {'legajo': 9999, 'nombre': 'LUCIA', 'apellido': 'PARDINI', 'fecha_ing': '1800-12-12', 'tipo_doc': 'DU', 'nro_doc': '99999999', 'convenio': 'CONVENIO TEST', 'cliente_id': 1, 'puesto': 'Sin definir', 'cargo': 'Sin definir', 'telefono': None}}]}

In [ ]:
# realizar importacion con verificacion (prueba)
if resultados['estadisticas']['nuevos'] > 0:
    resultado_importación = importar_datos(muestra_personal, api_url=API_URL2, api_token=API_KEY2)
    print(resultado_importación['message'])

Usando autenticación por token
Importacion exitosa